language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database anforadb;' -U postgres
install:
  - pip install pipenv
  - pipenv --python 3.6
  - pipenv install 
script:
  - export VENV_HOME_DIR=$(pipenv --venv)
  - export POPULATE=travis
  - export REDIS_HOST=localhost
  - source $VENV_HOME_DIR/bin/activate
  - cd src/
  - python populate.py
  - python -m pytest tests/