language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv --python 3.6
  - pipenv install 
script:
  - export VENV_HOME_DIR=$(pipenv --venv)
  - source $VENV_HOME_DIR/bin/activate
  - cd src/
  - python -m pytest tests/