# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.6-jessie-browsers-legacy
        environment:
          POPULATE: travis
          REDIS_HOST: localhost
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:10.3-alpine
      - image: circleci/redis:4.0.9-alpine

    working_directory: ~/anfora

    steps:
      - checkout

      - restore_cache:
          keys: 
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install --dev

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: setup env
          command: |
            echo 'export VENV_HOME_DIR=$(pwd)' >> $BASH_ENV
            mkdir uploads
            mkdir uploads/avatars
            mkdir uploads/max_resolution
            mkdir uploads/small

      - run:
          name: run tests
          command: |
            cd user-microservice
           	poetry run pytest tests/
          