[package]
name = "image_api"
version = "0.1.0"
authors = ["Yabir G. <yabirg@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.4.0"