# Public data
application_name: 'Anfora'
server_description: ''

# http config
scheme: 'http'
domain: 'localhost'

# Positition
root_path: '/home/yabir/anfora'

# Storage

media_folder: '/home/yabir/uploads'
thumb_folder: 'small'
image_folder: 'max_resolution'
icons_folder: 'icons'

# Uri salt

salt_code: 'whySoSalty?'

# DB

db_user: 'anforaUser'
db_port: '5432'
db_host: 'localhost'
db_name: 'anforadb'