# Public data
application_name: 'Anfora'
server_description: ''

# http config
scheme: 'http'
domain: 'localhost'

# Storage

media_folder: '/home/yabir/killMe/uploads'
thumb_folder: 'small'
image_folder: 'max_resolution'
icons_folder: 'icons'

# Uri salt

salt_code: 'whySoSalty?'