# Public data
application_name: 'Anfora'
server_description: ''

# http config
scheme: 'http'
domain: 'localhost'
port: '3000'

# Positition
root_path: '/home/yabir/anfora'

# Storage

media_folder: '/home/yabir/uploads'
thumb_folder: 'small'
image_folder: 'max_resolution'
icons_folder: 'icons'

# Uri salt

salt_code: 'whySoSalty?'

# DB

db_user: 'anforaUser'
db_pwd: 'anforaPwd'
db_port: '5432'
db_host: 'localhost'
db_name: 'anforadb'

#email

email_enabled: y # "y" for yes - "n" for no

smtp_server: ''
smtp_port: ''
smtp_login: ''
smtp_password: ''
smtp_adress: ''